[ScalabilitySettings]
PerfIndexValues_ResolutionQuality="50 70 85 100 100"

[ViewDistanceQuality@0]
r.ViewDistanceScale=0.5
r.SkeletalMeshLODBias=1
r.StaticMeshLODDistanceScale=2.0
foliage.MinimumScreenSize=0.01
foliage.LODDistanceScale=0.4

[ViewDistanceQuality@1]
r.SkeletalMeshLODBias=1
r.StaticMeshLODDistanceScale=1.5
foliage.MinimumScreenSize=0.01
foliage.LODDistanceScale=0.6

[ViewDistanceQuality@2]
r.SkeletalMeshLODBias=0
r.StaticMeshLODDistanceScale=1.25
foliage.MinimumScreenSize=0.01
foliage.LODDistanceScale=0.8

[ViewDistanceQuality@3]
r.SkeletalMeshLODBias=0
r.StaticMeshLODDistanceScale=1.0
foliage.MinimumScreenSize=0.01
foliage.LODDistanceScale=1.0

[ViewDistanceQuality@Cine]
r.SkeletalMeshLODBias=0
r.StaticMeshLODDistanceScale=1.0
foliage.MinimumScreenSize=0.001
foliage.LODDistanceScale=1.0

; Don't allow real time reflection captures to be disabled on lower settings, they are necessary so shadows aren't completely black
[EffectsQuality@0]
r.SkyLight.RealTimeReflectionCapture=1

[EffectsQuality@1]
r.SkyLight.RealTimeReflectionCapture=1

; Never use scene color format 4, it causes a glitch on some systems where the screen turns white when the sun and it's reflection are visible at the same time at high effects quality
[EffectsQuality@3]
r.SceneColorFormat=3

[EffectsQuality@Cine]
r.SceneColorFormat=3

; Don't set the light draw distance to zero on low quality, because zero actually means infinite
[ShadowQuality@0]
r.LightMaxDrawDistanceScale=0.5

[ShadowQuality@1]
r.LightMaxDrawDistanceScale=0.75

[PostProcessQuality@0]
r.BloomQuality=0

[PostProcessQuality@1]
r.BloomQuality=3